{
    "value0": {
        "T_imu_cam": [
            {
                "px": 0.27,
                "py": 0.06,
                "pz": 0.035,
                "qx": 0.5,
                "qy": -0.5,
                "qz": 0.5,
                "qw": 0.5
            },
            {
                "px": 0.27,
                "py": -0.06,
                "pz": 0.035,
                "qx": 0.5,
                "qy": -0.5,
                "qz": 0.5,
                "qw": 0.5
            }
        ],        
        "intrinsics": [
            {
                "camera_type": "pinhole",
                "intrinsics": {
                    "fx": 337.22195,
                    "fy": 337.22195,
                    "cx": 320.5,
                    "cy": 240.5
                }
            },
            {
                "camera_type": "pinhole",
                "intrinsics": {
                    "fx": 337.22195,
                    "fy": 337.22195,
                    "cx": 320.5,
                    "cy": 240.5
                }
            }
        ],
        "resolution": [
            [
                640,
                480
            ],
            [
                640,
                480
            ]
        ],
        "vignette": [
            {
                "value0": 0,
                "value1": 50000000000,
                "value2": [
                    [
                         1.0
                    ],
                    [
                         1.0
                    ],
                    [
                         1.0
                    ],
                    [
                         1.0
                    ],
                    [
                         1.0
                    ],
                    [
                         0.977014799737916
                    ],
                    [
                         0.963099657065011
                    ],
                    [
                         0.922192868484681
                    ],
                    [
                         0.854947649264748
                    ],
                    [
                         0.775979681731632
                    ],
                    [
                         0.722888431826212
                    ],
                    [
                         0.0686113338332548
                    ],
                    [
                         0.0686113338332548
                    ],
                    [
                         0.0686113338332548
                    ],
                    [
                         0.0686113338332548
                    ]
                ]
            },
            {
                "value0": 0,
                "value1": 50000000000,
                "value2": [
                    [
                         1.0
                    ],
                    [
                         1.0
                    ],
                    [
                         1.0
                    ],
                    [
                         1.0
                    ],
                    [
                         1.0
                    ],
                    [
                         0.977014799737916
                    ],
                    [
                         0.963099657065011
                    ],
                    [
                         0.922192868484681
                    ],
                    [
                         0.854947649264748
                    ],
                    [
                         0.775979681731632
                    ],
                    [
                         0.722888431826212
                    ],
                    [
                         0.0686113338332548
                    ],
                    [
                         0.0686113338332548
                    ],
                    [
                         0.0686113338332548
                    ],
                    [
                         0.0686113338332548
                    ]
                ]
            }
        ],
        "calib_accel_bias": [
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0
      ],
      "calib_gyro_bias": [
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0
      ],
        "imu_update_rate": 250.0,
        "accel_noise_std": [
            0.0001,
            0.0001,
            0.0001
        ],
        "gyro_noise_std": [
            0.000001,
            0.000001,
            0.000001
        ],
        "accel_bias_std": [
            0.00001,
            0.00001,
            0.00001
        ],
        "gyro_bias_std": [
            0.000001,
            0.000001,
            0.000001
        ],
        "T_imu_marker": {
            "px": 0.0,
            "py": 0.0,
            "pz": 0.0,
            "qx": 0.0,
            "qy": 0.0,
            "qz": 0.0,
            "qw": 1.0
        },
        "cam_time_offset_ns": 0
    }
}
